language: rust
script: cargo build && cargo test
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly

branches:
    only:
        - auto

notifications:
    webhooks: http://homuslice.herokuapp.com/travis
